name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.TF_VAR_aws_region }}
#      TF_VAR_key: ${{ secrets.KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure Terraform credentials
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$TF_API_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform init -force-copy

      - name: Terraform Destroy
        env:
          TF_LOG: INFO
        run: terraform destroy -auto-approve -input=false
